<a href="https://colab.research.google.com/github/Danish-Hussain-DSAI/final-year-project-workin-on-4k-images-deepfake-image-detection/blob/main/final_year_project_combined.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import os
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score



In [ ]:
!pip install filterpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.0/178.0 kB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110459 sha256=57be8ce3b9cfcb59bfe8fc33a0573e1ecaed55ec46b09815e05c5f4d7345a077
  Stored in directory: /root/.cache/pip/wheels/0f/0c/ea/218f266af4ad626897562199fbbcba521b8497303200186102
Successfully built filterpy


In [ ]:
import os
import cv2
import numpy as np
from filterpy.kalman import KalmanFilter

# Mount Google Drive to access the images
from google.colab import drive
drive.mount('/content/drive')

# Path to the folder containing images
folder_path = "/content/drive/MyDrive/fyp/real/real"

# Get a list of image files in the folder
image_files = [f for f in os.listdir(folder_path) if f.endswith(('.jpg', '.png'))]

# Function to apply Kalman filter to an image
def denoise_image_with_kalman(image):
    # Convert the image to grayscale
    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

       # Initialize Kalman filter
    kf = KalmanFilter(dim_x=1, dim_z=1)
    kf.x = np.array([image_gray[0, 0]], dtype=np.float64)  # Initial estimate (noisy pixel value)
    kf.F = np.array([[1]], dtype=np.float64)  # State transition matrix
    kf.H = np.array([[1]], dtype=np.float64)  # Measurement matrix
    kf.P *= 0.1  # Covariance matrix


      # Initialize filtered image (denoised image)
    filtered_image = np.zeros_like(image_gray, dtype=np.uint8)



        # Apply Kalman filter to denoise the image
    for i in range(image_gray.shape[0]):
        for j in range(image_gray.shape[1]):
            measurement = np.array([[image_gray[i, j]]], dtype=np.float64)  # Measurement (noisy pixel value)
            kf.predict()
            kf.update(measurement)
            filtered_image[i, j] = kf.x[0]


    return filtered_image

# Create a directory to save the denoised images
output_folder = "/content/drive/MyDrive/kalman filter/kalman real images"
os.makedirs(output_folder, exist_ok=True)

real_images=[]
max_images=2000
loaded_images=0
# Load each image, denoise using Kalman filter, and save the results
for image_file in image_files:

    if loaded_images >= max_images:
        break
    loaded_images+=1
    image_path = os.path.join(folder_path, image_file)
    image = cv2.imread(image_path)
    print(loaded_images)

    #image resizing
    img_resized = cv2.resize(image,(128,128), interpolation=cv2.INTER_AREA)


    #applying kalman filter
    filtered_image = denoise_image_with_kalman(img_resized)


    real_images.append(filtered_image)
    # Save the denoised image to the output folder
    # output_path = os.path.join(output_folder, image_file)
    # cv2.imwrite(output_path, filtered_image)

print("Denoising complete. Denoised images are saved in the output folder.")


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245

In [ ]:
import os
import cv2
import numpy as np
from filterpy.kalman import KalmanFilter

# Mount Google Drive to access the images
from google.colab import drive
drive.mount('/content/drive')

# Path to the folder containing images
folder_path = "/content/drive/MyDrive/fyp/fake/fake"

# Get a list of image files in the folder
image_files = [f for f in os.listdir(folder_path) if f.endswith(('.jpg', '.png'))]

# Function to apply Kalman filter to an image
def denoise_image_with_kalman(image):
    # Convert the image to grayscale
    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

       # Initialize Kalman filter
    kf = KalmanFilter(dim_x=1, dim_z=1)
    kf.x = np.array([image_gray[0, 0]], dtype=np.float64)  # Initial estimate (noisy pixel value)
    kf.F = np.array([[1]], dtype=np.float64)  # State transition matrix
    kf.H = np.array([[1]], dtype=np.float64)  # Measurement matrix
    kf.P *= 0.1  # Covariance matrix


      # Initialize filtered image (denoised image)
    filtered_image = np.zeros_like(image_gray, dtype=np.uint8)



        # Apply Kalman filter to denoise the image
    for i in range(image_gray.shape[0]):
        for j in range(image_gray.shape[1]):
            measurement = np.array([[image_gray[i, j]]], dtype=np.float64)  # Measurement (noisy pixel value)
            kf.predict()
            kf.update(measurement)
            filtered_image[i, j] = kf.x[0]


    return filtered_image

# Create a directory to save the denoised images
output_folder = "/content/drive/MyDrive/kalman filter/kalman fake images"
os.makedirs(output_folder, exist_ok=True)


fake_images=[]
loaded_fake_images=0
max_fake_images=2000
# Load each image, denoise using Kalman filter, and save the results
for image_file in image_files:

    if loaded_fake_images>=max_fake_images:
      break

    loaded_fake_images+=1
    image_path = os.path.join(folder_path, image_file)
    image = cv2.imread(image_path)
    print(loaded_fake_images)

    #image resizing
    img_resized = cv2.resize(image,(128,128), interpolation=cv2.INTER_AREA)


    #applying kalman filter
    filtered_image = denoise_image_with_kalman(img_resized)


    fake_images.append(filtered_image)
    # # Save the denoised image to the output folder
    # output_path = os.path.join(output_folder, image_file)
    # cv2.imwrite(output_path, filtered_image)

print("Denoising complete. Denoised images are saved in the output folder.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245

In [ ]:

# Set the paths to the real and fake image folders
real_folder = "/content/drive/MyDrive/kalman filter/kalman real images"
fake_folder = "/content/drive/MyDrive/kalman filter/kalman fake images"

# Initialize lists to store images and labels



X = []
Y = []


# Load real images and assign the label 'real'
for i in real_images:
    print(i)
    X.append(i)
    Y.append(1)


# Load fake images and assign the label 'fake'
for j in fake_images:

    print(j)
    X.append(j)
    Y.append(0)

# Convert lists to numpy arrays
X = np.array(X)
Y = np.array(Y)


Streaming output truncated to the last 5000 lines.
 [236 237 237 ... 234 234 234]
 [237 238 228 ... 231 233 232]]
[[145 144 145 ... 142 140 143]
 [144 144 146 ... 145 142 144]
 [145 145 146 ... 143 141 145]
 ...
 [155 155 152 ... 135 133 135]
 [152 154 154 ... 133 134 137]
 [151 157 161 ... 129 130 138]]
[[164 167 174 ... 216 219 220]
 [185 176 177 ... 214 219 221]
 [186 178 178 ... 211 216 219]
 ...
 [118 150 163 ...  34  35  37]
 [117 150 164 ...  34  32  35]
 [118 152 165 ...  32  32  34]]
[[185 185 184 ... 187 188 192]
 [187 185 185 ... 186 187 187]
 [186 185 185 ... 185 184 185]
 ...
 [165 175 178 ... 143 141 134]
 [165 176 180 ... 143 137 130]
 [167 178 180 ... 135 126 121]]
[[191 189 187 ... 120 129 132]
 [170 181 184 ... 124 136 137]
 [174 185 185 ... 127 142 145]
 ...
 [ 63  63  61 ...  55  52  50]
 [ 85  95  94 ...  54  45  42]
 [ 93 109 111 ...  55  45  41]]
[[22 20 18 ... 20 20 22]
 [20 20 18 ... 21 20 18]
 [18 19 19 ... 20 18 18]
 ...
 [77 77 73 ... 56 69 77]
 [74 76 75 ..

In [ ]:
#normalization
X=X/255.0

print(X)

[[[1.         0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]
  ...
  [0.99607843 0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843 ... 0.99607843 0.99607843 0.99607843]]

 [[0.74509804 0.74509804 0.74509804 ... 0.77647059 0.77647059 0.77647059]
  [0.75686275 0.75294118 0.75294118 ... 0.77647059 0.77254902 0.77254902]
  [0.76078431 0.75294118 0.75294118 ... 0.77647059 0.77647059 0.77647059]
  ...
  [0.5254902  0.4        0.34117647 ... 0.74901961 0.74901961 0.74901961]
  [0.52156863 0.38823529 0.3372549  ... 0.74901961 0.74509804 0.74509804]
  [0.54117647 0.42745098 0.34509804 ... 0.74509804 0.74509804 0.74509804]]

 [[0.74117647 0.74117647 0.74117647 ... 0.71372549 0.71372549 0.71372549]
  [0.72941176 0.737254

In [ ]:
np.shape(X)

(4000, 128, 128)

In [ ]:
print("number of input images : ",np.shape(X))
print("number of labels : ",np.shape(Y))

number of input images :  (4000, 128, 128)
number of labels :  (4000,)


In [ ]:
from sklearn.utils import shuffle

# Shuffle the data while keeping labels synchronized
X, Y = shuffle(X, Y, random_state=42)


In [ ]:
import cv2
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from skimage.feature import local_binary_pattern

# Load your dataset, X (images) and Y (encoded labels).

# Initialize lists to store features
features = []

# Extract features (e.g., LBPH) from the images
for image in X:


    # Compute the Local Binary Pattern (LBP) texture features
    radius = 1
    n_points = 8 * radius
    lbp_image = local_binary_pattern(image, n_points, radius, method='uniform')

    # Compute a histogram of the LBP image
    hist, _ = np.histogram(lbp_image.ravel(), bins=np.arange(0, n_points + 3), range=(0, n_points + 2))

    # Normalize the histogram
    hist = hist.astype("float")
    hist /= (hist.sum() + 1e-6)

    # Append the LBP histogram as a feature
    features.append(hist)

# Convert the features to a NumPy array
features = np.array(features)

# Apply Fisherfaces for dimensionality reduction
lda = LinearDiscriminantAnalysis(n_components=1)  # Choose the number of components you want
reduced_features = lda.fit_transform(features, Y)  # Assuming Y is already encoded

# The variable reduced_features now contains the reduced feature vectors.

# You can use the reduced feature vectors for further processing, such as classification or recognition tasks.


In [ ]:
X=np.array(reduced_features)
np.shape(X)

(4000, 1)

In [ ]:
X = X.reshape(X.shape[0], -1)

In [ ]:
print(np.shape(X))
print(np.shape(Y))

(4000, 1)
(4000,)


In [ ]:
from sklearn.model_selection import train_test_split

# Assuming X contains features and Y contains labels
# Adjust test_size as needed (e.g., 0.2 for 80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Print the shapes to verify
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)


X_train shape: (3200, 1)
X_test shape: (800, 1)
Y_train shape: (3200,)
Y_test shape: (800,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN classifier object
knn = KNeighborsClassifier(n_neighbors=5)

# Train the KNN classifier on the extracted features
knn.fit(X_train, Y_train)

# Make predictions on the test data
y_pred = knn.predict(X_test)

# Calculate the accuracy of the model
accuracy = np.mean(y_pred == Y_test)

# Print the accuracy
print('Accuracy:', accuracy)


Accuracy: 0.51


In [ ]:
# Train Logistic Regression
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, Y_train)
logistic_predictions = logistic_regression.predict(X_test)
logistic_accuracy = accuracy_score(Y_test, logistic_predictions)
print('Logistic Regression Accuracy:', logistic_accuracy)

Logistic Regression Accuracy: 0.56


In [ ]:
# Train Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
decision_tree_predictions = decision_tree.predict(X_test)
decision_tree_accuracy = accuracy_score(Y_test, decision_tree_predictions)
print('Decision Tree Accuracy:', decision_tree_accuracy)


Decision Tree Accuracy: 0.5325


In [ ]:
# Train Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(X_train, Y_train)
random_forest_predictions = random_forest.predict(X_test)
random_forest_accuracy = accuracy_score(Y_test, random_forest_predictions)
print('Random Forest Accuracy:', random_forest_accuracy)

Random Forest Accuracy: 0.5325


In [ ]:
from sklearn.svm import SVC



# Step 2: Train the SVM classifier
svm_classifier = SVC(kernel='linear')  # Linear SVM, you can try other kernels as well
svm_classifier.fit(X_train, Y_train)

# Step 3: Predict on test data
svm_predictions = svm_classifier.predict(X_test)

# Step 4: Calculate accuracy
svm_accuracy = accuracy_score(Y_test, svm_predictions)

print('SVM Accuracy:', svm_accuracy)


SVM Accuracy: 0.56375


In [ ]:
import numpy as np
import cv2
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# Load your dataset, X_train, Y_train, X_test, and Y_test are already defined.

# Preprocess the images (resize and normalize)
X_train = np.array([cv2.resize(image, (64, 64)) for image in X_train])
X_test = np.array([cv2.resize(image, (64, 64)) for image in X_test])
X_train = X_train / 255.0  # Normalize pixel values to the range [0, 1]
X_test = X_test / 255.0

# Add a channel dimension to the images (assuming grayscale images)
X_train = X_train[..., np.newaxis]
X_test = X_test[..., np.newaxis]

# Encode class labels as numeric values
label_encoder = LabelEncoder()
Y_train = label_encoder.fit_transform(Y_train)
Y_test = label_encoder.transform(Y_test)

# Create a CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')  # Assuming two classes
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, epochs=10)

# Evaluate the model
Y_pred = model.predict(X_test)
predicted_classes = np.argmax(Y_pred, axis=1)
accuracy = accuracy_score(Y_test, predicted_classes)

print(f"Accuracy: {accuracy:.2f}")


Epoch 1/10
100/100 [==============================] - 16s 143ms/step - loss: 0.6936 - accuracy: 0.4853
Epoch 2/10
100/100 [==============================] - 13s 126ms/step - loss: 0.6934 - accuracy: 0.4975
Epoch 3/10
100/100 [==============================] - 11s 106ms/step - loss: 0.6932 - accuracy: 0.5006
Epoch 4/10
100/100 [==============================] - 11s 106ms/step - loss: 0.6932 - accuracy: 0.4931
Epoch 5/10
100/100 [==============================] - 11s 106ms/step - loss: 0.6932 - accuracy: 0.5006
Epoch 6/10
100/100 [==============================] - 10s 99ms/step - loss: 0.6932 - accuracy: 0.5006
Epoch 7/10
100/100 [==============================] - 10s 102ms/step - loss: 0.6932 - accuracy: 0.5006
Epoch 8/10
100/100 [==============================] - 11s 106ms/step - loss: 0.6933 - accuracy: 0.4900
Epoch 9/10
100/100 [==============================] - 11s 106ms/step - loss: 0.6932 - accuracy: 0.4981
Epoch 10/10
25/25 [==============================] - 1s 28ms/step
Accuracy